// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5rX5IYagd6lzFyANm7uZIdTbpM_w-8lQ',
    appId: '1:840998826082:web:b2b4466ac566c203b2e13b',
    messagingSenderId: '840998826082',
    projectId: 'atti-5d394',
    authDomain: 'atti-5d394.firebaseapp.com',
    storageBucket: 'atti-5d394.firebasestorage.app',
    measurementId: 'G-8JRLZNZEDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfVOGRiCCOJfbC1EOHg26lRsDjVdR6Rto',
    appId: '1:840998826082:android:2939b5a0dfef3823b2e13b',
    messagingSenderId: '840998826082',
    projectId: 'atti-5d394',
    storageBucket: 'atti-5d394.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcdaXtf3302msqTTbfWVVd7YmDJCqynho',
    appId: '1:840998826082:ios:ecca05205ce46c9fb2e13b',
    messagingSenderId: '840998826082',
    projectId: 'atti-5d394',
    storageBucket: 'atti-5d394.firebasestorage.app',
    iosBundleId: 'com.example.teacher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcdaXtf3302msqTTbfWVVd7YmDJCqynho',
    appId: '1:840998826082:ios:ecca05205ce46c9fb2e13b',
    messagingSenderId: '840998826082',
    projectId: 'atti-5d394',
    storageBucket: 'atti-5d394.firebasestorage.app',
    iosBundleId: 'com.example.teacher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5rX5IYagd6lzFyANm7uZIdTbpM_w-8lQ',
    appId: '1:840998826082:web:800beec899e9398db2e13b',
    messagingSenderId: '840998826082',
    projectId: 'atti-5d394',
    authDomain: 'atti-5d394.firebaseapp.com',
    storageBucket: 'atti-5d394.firebasestorage.app',
    measurementId: 'G-N0EZZCKL3D',
  );
}
